# Generated by Django 2.2.9 on 2021-07-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_year', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=70)),
                ('student_age', models.IntegerField()),
                ('student_gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=70)),
                ('course_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolinfo.course_year')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolinfo.department')),
            ],
        ),
        migrations.CreateModel(
            name='professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_name', models.CharField(max_length=70)),
                ('professor_age', models.CharField(max_length=70)),
                ('professor_gender', models.CharField(max_length=70)),
                ('professor_subject', models.CharField(max_length=70)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolinfo.department')),
            ],
        ),
    ]
